### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by abetusk** [veekaybee/what_are_embeddings#23]
On the web page (source [here](https://github.com/veekaybee/what_are_embeddings/blob/site/docs/index.html#L319)) the license is stated as CC-BY-SA 3.0 (Creative Commons, By Attribution, Share Alike 3.0) yet in the paper ([here](https://raw.githubusercontent.com/veekaybee/what_are_embeddings/main/embeddings.pdf)) the license is CC-BY-NC-SA 3.0 (Creative Commons, By Attribution, Non-Commercial, Share Alike 3.0).

If the intent is to restrict commercial re-use, then the text on the web page should be changed to CC-BY-NC-SA 3.0 to reflect what license the PDF document is under. If the intent is to allow for commercial re-use and to make the document libre/free in the open source sense, the license should be changed to CC-BY-SA 3.0 in the PDF document.

**Comment by veekaybee** [comment]
Fixed by this, thanks for the note! https://github.com/veekaybee/what_are_embeddings/commit/3bab062aef93b4ffb0c94102adfc6f7520b3df1f
