### ISSUE TITLE
Kindle friendly PDF?

### ISSUE THREAD

**Issue by ivoras** [veekaybee/what_are_embeddings#24]
Hello!

Thanks for writing the book - the stuff I've read so far (the intro) seems very well explained and easy to read! 

However, I'm trying to read it on Kindle Paperwhite and everything is just tiny, as the PDF pages are flowed for A4 pages.
Since it appears to be written in TeX, could you please generate a Kindle-friendly version? The screen dimensions are closest to B7 (and please use narrow margins, the device has a large bezel itself :) ).

Thanks again in any case!

**Comment by veekaybee** [comment]
Thanks for filing this issue! I  don't have bandwidth to change the file and even if I did, no way to test a filed PR since I don't have a Kindle, but feel free to fork the repo and generate it - the .tex and .bib files are included.
