### ISSUE TITLE
Please include a link to the website in the PDF

### ISSUE THREAD

**Issue by domesticmouse** [veekaybee/what_are_embeddings#32]
I really appreciate your paper on embeddings, but I feel that a paragraph in the introduction that links back to [the book's website](https://vickiboykis.com/what_are_embeddings/) along with a version indicator would help me establish if the PDF I have is current and can be read as is, or if it is out dated and should be deleted and re-downloaded.

Also, it helps if I send the PDF to someone instead of just sending them a link to your website. =)

**Comment by veekaybee** [comment]
Hi Brett, thanks so much for the comment. There's a link to the website and the GitHub in the intro - hope this is helpful. 
 
<img width="718" alt="Screenshot 2023-08-20 at 10 59 47 AM" src="https://github.com/veekaybee/what_are_embeddings/assets/3837836/299078ef-0178-4b9a-a3dd-01697a58e98f">
