### ISSUE TITLE
Possibly a bug in tf-idf

### ISSUE THREAD

**Issue by AwesomeLemon** [veekaybee/what_are_embeddings#36]
I believe there may be a bug in the ``idf`` function in https://github.com/veekaybee/what_are_embeddings/blob/main/notebooks/fig_24_tf_idf_from_scratch.ipynb

Namely, the number of documents in which a term appears does not seem to be actually computed, just initialized to 0.

You could see that the results are wrong by looking at the printed tf-idf values for document 0 for words "a" and "bird": the printed values are equal, which doesn't make sense: although tf for both of them is the same (since they each appear in the document0 once), idf should be different, since "a" appears only in document0, and "bird" appears in document0 and document1.

**Comment by veekaybee** [comment]
Addressed with https://github.com/veekaybee/what_are_embeddings/pull/37

Thank you both!
