### ISSUE TITLE
Gensim Link broken?

### ISSUE THREAD

**Issue by jul-carras** [veekaybee/what_are_embeddings#38]
Hi! I'm working through the embeddings write up and it's a fantastic read.

In my copy that I downloaded a little while ago, the hyperlink for "Gensim" on page 44 just goes to the first page of the document. I went to make a pr, but [this line looks to have the correct url](https://github.com/veekaybee/what_are_embeddings/blob/main/embeddings.tex#L1560C207-L1560C239). I downloaded a fresh copy from [the main page](https://vickiboykis.com/what_are_embeddings/), but the link still goes to the top of the document and doesn't have hyperlink format. 

![image](https://github.com/veekaybee/what_are_embeddings/assets/9213584/8eee6d52-3a2b-41f5-a2dc-1ec9699d9c6d)
 
I think the main site needs to get a fresh version of the pdf?

**Comment by veekaybee** [comment]
Thanks for this! Should be fixed now, the error was the wrong latex directive https://github.com/veekaybee/what_are_embeddings/commit/9c8e6e333ad615ab2ef0a1a01bf09a01bfeaf35b
