### ISSUE TITLE
Give an intuition of the `dict_a` and `dict_b` in the tf-idf example

### ISSUE THREAD

**Issue by EdwinTh** [veekaybee/what_are_embeddings#39]
Loving your document so far, Vicky! (filing this as I read)

In the tf-idf example on [page 33](https://github.com/veekaybee/what_are_embeddings/blob/main/embeddings.tex#L1144) the objects `dict_a` and `dict_b` appear all of a sudden. I could not derive from the example what they represent and had to open the total on example on github to understand. Even though it is a truncated implementation I think some explanation on these objects would enhance the example. If nothing else, by just adding a code comment what they are / where they are coming from.

**Comment by veekaybee** [comment]
Sure thing, hope this his helpful: https://github.com/veekaybee/what_are_embeddings/commit/d5668eaafbf1f3db7b8c1f804c82a1ecf7445374
