### ISSUE TITLE
Source links broken for Figures 36 and 37

### ISSUE THREAD

**Issue by AndrewRook** [veekaybee/what_are_embeddings#45]
Hi! First of all, this is great! Thank you so much for putting all of this together, it has been incredibly helpful so far. 

I've been trying to follow the source code for the figures and found that both Figures 36 and 37 point to [https://github.com/veekaybee/viberary/tree/main/word2vec](https://github.com/veekaybee/viberary/tree/main/word2vec), which unfortunately no longer seems to exist. I tried to poke around the Viberary repo a bit to see if I could find where the source had been moved to but I couldn't figure it out. If you point me in the right direction I can probably make a PR with the corrected links.

**Comment by veekaybee** [comment]
Thanks so much for opening this issue! You're right that these links are missing, I believe they were from previous branches that were deleted. 🤦‍♀️  If you're up for making a change, I'd recommend the following two:

1. Remove the link in figure 36
2. Repoint the link in figure 37 to https://github.com/veekaybee/viberary/blob/722c4b576bf1bdaf59c806661b23bd3afaabf883/src/notebooks/cbow.ipynb#L12

Let me know if that works, if not happy to take it.
